# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Zalenium Server 
    steps:
    - uses: actions/checkout@v2
    - name: Start Zalenium Server
      uses: ajinx/zalenium@v1.1
    - name: Run test
      env:
        SELENIUM_HUB_HOST: 'localhost'
      run: mvn clean test -Denvironment=qa -DHUB_HOST=http://localhost:4444/wd/hub
